config/routes.rb
DisMardisOrdering::Application.routes.draw do
  get  "usuarios/cambiar_password"
  post "usuarios/cambiar_password"
  
  resources :estado_pedidos

  resources :provincia

  resources :ciudads

  resources :familia

  resources :categoria

  resources :proveedors

  get  "usuarios/login"
  post "usuarios/login"
  
  get  "usuarios/logout"
  
  get  "usuarios/nuevo_gerente"
  post "usuarios/nuevo_gerente"
  get  "usuarios/nuevo_cajero"
  post "usuarios/nuevo_cajero"
  get  "usuarios/nuevo_cliente"
  post "usuarios/nuevo_cliente"

  resources :pedidos
  match 'pedidos/:id/responder_pedido', :to => 'pedidos#responder_pedido'
  
  
  resources :session
  resources :productos

  resources :agencia

  resources :tipo_usuarios

  resources :usuarios

  get  "home/index"
  get  "home/forbidden"

  root :to => 'home#index'

end

app/models/ciudad.rb
class Ciudad < ActiveRecord::Base
  belongs_to :provincia, :class_name => "Provincium", :foreign_key => "idProvincia"
  has_many :Usuario
end

app/controllers/ciudads_controller.rb
class CiudadsController < ApplicationController
  before_filter :check_permissions
  
  # GET /ciudads
  # GET /ciudads.json
  def index
    @ciudads = Ciudad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ciudads }
    end
  end

  # GET /ciudads/1
  # GET /ciudads/1.json
  def show
    @ciudad = Ciudad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ciudad }
    end
  end

  # GET /ciudads/new
  # GET /ciudads/new.json
  def new
    @ciudad = Ciudad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ciudad }
    end
  end

  # GET /ciudads/1/edit
  def edit
    @ciudad = Ciudad.find(params[:id])
  end

  # POST /ciudads
  # POST /ciudads.json
  def create
    @ciudad = Ciudad.new(params[:ciudad])

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to ciudads_path, notice: 'Ciudad fue creada exitosamente.' }
        format.json { render json: @ciudad, status: :created, location: @ciudad }
      else
        format.html { render action: "new" }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ciudads/1
  # PUT /ciudads/1.json
  def update
    @ciudad = Ciudad.find(params[:id])

    respond_to do |format|
      if @ciudad.update_attributes(params[:ciudad])
        format.html { redirect_to @ciudad, notice: 'Ciudad fue actualizada existosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudads/1
  # DELETE /ciudads/1.json
  def destroy
    @ciudad = Ciudad.find(params[:id])
    @ciudad.destroy

    respond_to do |format|
      format.html { redirect_to ciudads_url }
      format.json { head :no_content }
    end
  end
  
  private
    def check_permissions
      if session[:Usuario_idTP] == 3 || session[:Usuario_idTP] == 4
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 2 && self.action_name == 'destroy'
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
    end
end

app/helpers/ciudads_helper.rb
module CiudadsHelper
end

app/views/ciudads/_form.html.erb
<%= form_for(@ciudad) do |f| %>
  <% if @ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>

      <ul>
      <% @ciudad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :idProvincia %><br />
    <%= f.number_field :idProvincia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ciudads/edit.html.erb
<h1>Editar Ciudad</h1>

<%= form_for (@ciudad) do |f| -%>
	
	  
	<fieldset>
		<legend><h2>Formulario</h2></legend>
		<p>
			<%= f.label 'Nombre' %><br />
		    <%= f.text_field :Nombre , :autocomplete => :off, :autofocus => true%>
		</p>
		<p>
	  	  <%= f.label 'Provincia' %><br />
	  	  <%= f.collection_select :idProvincia, Provincium.all, :id, :Nombre %>
	    </p>
    </fieldset>
  
  <p><%= f.submit "Actualizar Ciudad" %></p>
<% end %>

<%= link_to 'Volver a ' + @ciudad.Nombre, @ciudad %> |
<%= link_to 'Listado de Ciudades', ciudads_path %>

app/views/ciudads/index.html.erb
<h1>Listado Ciudades</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <% if session[:Usuario_idTP] == 1 %>
	 
	 	<th></th> 
	 
	<% end %>
  </tr>

<% @ciudads.each do |ciudad| %>
  <tr>
    <td><%= link_to ciudad.Nombre, ciudad %></td>
    <td><%= link_to 'Editar', edit_ciudad_path(ciudad) %></td>
    
    <% if session[:Usuario_idTP] == 1 %>
	 
	 	<td><%= button_to  'Borrar', ciudad, confirm: 'Esta seguro?', method: :delete %></td>
	 
	<% end %>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva Ciudad', new_ciudad_path %>

app/views/ciudads/new.html.erb
<h1>Nueva Ciudad</h1>


  <%= form_for :ciudad, :url => ciudads_path do |f| -%>
	
	  
	<fieldset>
		<legend><h2>Formulario</h2></legend>
		<p>
			<%= label_tag 'Nombre' %><br />
		    <%= f.text_field :Nombre , :autocomplete => :off, :autofocus => true%>
		</p>
		<p>
	  	  <%= label_tag 'Provincia' %><br />
	  	  <%= f.collection_select :idProvincia, Provincium.all, :id, :Nombre %>
	    </p>
    </fieldset>
  
  <p><%= submit_tag 'Crear Ciudad' %></p>
  <% end %>


<%= link_to 'Listado de Ciudades', ciudads_path %>

app/views/ciudads/show.html.erb
<p>
  <b>Nombre:</b>
  <%= @ciudad.Nombre %>
</p>

<p>
  <b>Provincia:</b>
  <%= @ciudad.provincia.Nombre %>
</p>


<%= link_to 'Editar', edit_ciudad_path(@ciudad) %> |
<%= link_to 'Listado de Ciudades', ciudads_path %>