config/routes.rb
DisMardisOrdering::Application.routes.draw do
  get  "usuarios/cambiar_password"
  post "usuarios/cambiar_password"
  
  resources :estado_pedidos

  resources :provincia

  resources :ciudads

  resources :familia

  resources :categoria

  resources :proveedors

  get  "usuarios/login"
  post "usuarios/login"
  
  get  "usuarios/logout"
  
  get  "usuarios/nuevo_gerente"
  post "usuarios/nuevo_gerente"
  get  "usuarios/nuevo_cajero"
  post "usuarios/nuevo_cajero"
  get  "usuarios/nuevo_cliente"
  post "usuarios/nuevo_cliente"

  resources :pedidos
  match 'pedidos/:id/responder_pedido', :to => 'pedidos#responder_pedido'
  
  
  resources :session
  resources :productos

  resources :agencia

  resources :tipo_usuarios

  resources :usuarios

  get  "home/index"
  get  "home/forbidden"

  root :to => 'home#index'

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  has_many :Producto, :through => Item
  belongs_to :user, :class_name => "Usuario", :foreign_key => "id_usuario"
  belongs_to :pestado, :class_name => "EstadoPedido", :foreign_key => "idEstado"


  validates :Codigo       ,  :length => {
                            :minimum   => 1,
                            :maximum   => 15,
                            :too_short => ": Debe de tener por lo menos %{count} letras.",
                            :too_long  => ": Debe de tener un maximo de %{count} letras."
                          },
                          :presence => { :message => ": No puede ser ingresado como en blanco." },
                          :uniqueness => { :case_sensitive => false ,  :message => ": No es unico." }

  validates :idEstado     , :numericality => { :only_integer => true },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }
  validates :id_usuario   , :numericality => { :only_integer => true },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }

  validates :Total        , :numericality => { :message => ": %{value} No es un valor valido." },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }




end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_filter :check_permissions
  
  #@@items
  # GET /pedidos
  # GET /pedidos.json
  def index
    if session[:Usuario_idTP] == 4
      @pedidos = Pedido.find(:all, :conditions =>  ["id_usuario = ? ", session[:Usuario_id]])
    else
      @pedidos = Pedido.all
    end
    #@pedidos = Pedido.count( :conditions =>  ["idUsuario = ? ", session[:Usuario_id]])
    #Pedido.where('idUsuario = ?', session[:Usuario_id]).all
    #@pedidos = Pedido.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedidos }
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])
    @items = Item.find(:all, :conditions =>  ["pedido_id = ? ", params[:id]])
    @sumTot = 0
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/new
  # GET /pedidos/new.json
  def new
    @pedido = Pedido.new
    @item3 = Item.new
    
    
    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  # GET /pedidos/1/edit
  def edit
    @pedido = Pedido.find(params[:id])
  end
  
  # GET /pedidos/1/edit
  def responder_pedido
    @pedido = Pedido.find(params[:id])
    @sumTot = 0
    
    @test1 = session[:Usuario_idTP] 
    @test2 = self.action_name
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @numPedidos = Pedido.count(:all, :conditions =>  ["id_usuario = ? ", session[:Usuario_id]])
    @usuario = Usuario.find(session[:Usuario_id])
    numPed_s = (@numPedidos + 1).to_s
    @item3 = Item.new
    if ((@numPedidos + 1) > 99999)
      #add more stuff here
      return
    end
    
    case numPed_s.length
      when 1
        numPed_s = "0000" + numPed_s 
      when 2
        numPed_s = "000" + numPed_s 
      when 3
        numPed_s = "00" + numPed_s 
      when 4
        numPed_s = "0" + numPed_s
    end 
    
    params[:pedido][:Codigo] = @usuario.codigo + "-" + numPed_s
    
    @pedido = Pedido.new(params[:pedido])
    @sumTot = 0
    @sumCant = 0
    
    
    respond_to do |format|
      
      checkGood = 0
      
      if @pedido.valid?
        params[:items].each do |item|
          if item[1].to_i > 0  && checkGood == 0
            #item2 = Producto.first(:all, :conditions =>  ["id = ? ", item[:id]])
            #item2 = Item.new(Integer(item[:id]),session[:Usuario_id],Integer(item[:value]))
            item2 = Item.new
            item2.pedido_id = 1 #@pedido.id
            item2.producto_id = item[0].to_i
            item2.cantidad = item[1].to_i
            @sumTot += (item2.cantidad * item2.prod.Precio)
            @item3 = item2
            if !(@item3.valid?)
              format.html { render action: "new" }
              format.json { render json: item2.errors, status: :unprocessable_entity }
              checkGood = 1
              #return
            end
            @sumCant = @sumCant + item[1].to_i
          end
        end
        @sumTot = @sumTot - (@sumTot * @pedido.user.Descuento)
        params[:pedido][:Total] = @sumTot
        if !(@pedido.valid?)  && checkGood == 0
          format.html { render action: "new" }
          format.json { render json: @pedido.errors, status: :unprocessable_entity }
          checkGood = 1
          #return
        end
        
        # Continue cause all is good
        
        #format.html { redirect_to @pedido, notice: 'El pedido fue creado exitosamente.' }
        #format.json { render json: @pedido, status: :created, location: @pedido }
        #return
      else
        #render :action => "new"
        format.html { render action: "new" }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
        checkGood = 1
        #return
      end
      
      
      
      if @sumCant.to_i == 0 && checkGood == 0
        #@pedido.errors.add :Total, "Para completar una orden se debe pedir por lo menos un producto."
        flash[:notice] = "Para completar una orden se debe pedir por lo menos un producto."
        format.html { render  "new" }
        #format.json { render json: @pedido.errors, status: :unprocessable_entity }
        checkGood = 1
      end
      
      
      
      ###############################################################################
      if checkGood == 0
        @sumTot = 0
        if @pedido.save
          params[:items].each do |item|
            if item[1].to_i > 0
              #item2 = Producto.first(:all, :conditions =>  ["id = ? ", item[:id]])
              #item2 = Item.new(Integer(item[:id]),session[:Usuario_id],Integer(item[:value]))
              item2 = Item.new
              item2.pedido_id = @pedido.id
              item2.producto_id = item[0].to_i
              item2.cantidad = item[1].to_i
              @sumTot += (item2.cantidad * item2.prod.Precio)
              item2.save
            end
          end
          @sumTot = @sumTot - (@sumTot * @pedido.user.Descuento)
          params[:pedido][:Total] = @sumTot
          if !(@pedido.update_attributes(params[:pedido]))
            format.html { render action: "new" }
            format.json { render json: @pedido.errors, status: :unprocessable_entity }
          end
          format.html { redirect_to @pedido, notice: 'El pedido fue creado exitosamente.' }
          format.json { render json: @pedido, status: :created, location: @pedido }
        else
          #render :action => "new"
          format.html { render action: "new" }
          format.json { render json: @pedido.errors, status: :unprocessable_entity }
        end
      end  
        
        
    end
  end

  # PUT /pedidos/1
  # PUT /pedidos/1.json
  def update
    @pedido = Pedido.find(params[:id])

    respond_to do |format|
      if @pedido.update_attributes(params[:pedido])
        format.html { redirect_to @pedido, notice: 'El pedido fue actualizado existosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "responder_pedido" } # cambiar cuando haya el segundo
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido = Pedido.find(params[:id])
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url }
      format.json { head :no_content }
    end
  end
  
  private
    def check_permissions
      if session[:Usuario_idTP] != 4 && (self.action_name == 'new' || self.action_name == 'create')
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 3 && (self.action_name != 'show' && self.action_name != 'index')
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 4 && self.action_name == 'destroy'
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 4 && (self.action_name != 'index' && self.action_name != 'new' && self.action_name != 'create')
        @pedido = Pedido.find(params[:id])
        if @pedido.user.id.to_s != session[:Usuario_id].to_s
          redirect_to  :controller => 'home', :action => 'forbidden'
          return
        end
      end
      if session[:Usuario_idTP] == 2 && self.action_name == 'destroy'
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
    end
    
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idUsuario %><br />
    <%= f.number_field :idUsuario %>
  </div>
  <div class="field">
    <%= f.label :Codigo %><br />
    <%= f.text_field :Codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Listado de Pedidos</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Usuario</th>
    <th>Fecha Pedido</th>
    <th>Estado</th>
    <th>Total</th>
  </tr>

  <% @pedidos.each do |pedido| %>
  <tr>
    <td><%= link_to pedido.Codigo, pedido %></td>
    <td><%= pedido.user.Username %></td>
    <td><%= pedido.FechaEntrega %></td>
    <td><%= pedido.pestado.Nombre %></td>
    <td><%= number_to_currency(pedido.Total, :precision => 2) %></td>
  </tr>
<% end %>
</table>

<br />

<% if session[:Usuario_idTP] == 4 %>
	<%= link_to 'Nuevo Pedido', new_pedido_path %>
<% end %>

app/views/pedidos/new.html.erb
<% @items = Item.find(:all, :conditions =>  ["Cantidad = ? ", -1]) 
 @productos = Producto.find(:all, :conditions =>  ["Estado = ? ", true]) 
 @productos.each do |producto|
      item = Item.new
      item.pedido_id = @pedido.id
      item.producto_id = producto.id
      item.cantidad = 0
      @items << item
    end 
 
 
 
 
    %>
  



<h1>Nuevo Pedido</h1>

<%= form_for :pedido, :url => pedidos_path do |f| -%>
      <% @pedido.errors.full_messages.each do |msg| %>
	    <p><%= msg %></p>
	  <% end %>
	  <% @item3.errors.full_messages.each do |msg| %>
	    <p><%= msg %></p>
	  <% end %>

<!-- :readonly => true -->
<p><%= f.hidden_field :Codigo, :value => "" %> </p>
<p><%= f.hidden_field :FechaPedido, :value => DateTime.now.strftime("%d/%m/%Y") %></p>
<p><%= f.hidden_field :idEstado, :value => 1 %></p>
<p><%= f.hidden_field :Total, :value => 0 %></p>


<p><%= f.hidden_field :id_usuario, :value => session[:Usuario_id] %> </p>


<p>
	
	<table>
	  <tr>
	  	<th>Categoria</th>
	  	<th>Familia</th>
	  	<th>Producto</th>
	  	<th>Presentacion</th>
	    <th>Codigo</th>
	    <th>Precio</th>
	    <th>Cantidad</th>
	  </tr>
	
	<% @items.each do |item| %>
	  <tr>
	  	<td><%= item.prod.fam.categ.Nombre %></td>
	  	<td><%= item.prod.fam.Nombre %></td>
	    <td><%= item.prod.Nombre %></td>
	    <td><%= item.prod.Presentacion %></td>
	    <td><%= item.prod.Codigo %></td>
	    <td><%= number_to_currency(item.prod.Precio, :precision => 2) %></td>
	    <td><%= text_field_tag "items[#{item.prod.id}]", item.cantidad, :id => "items_#{item.prod.id}", :autocomplete => :off%></td>
	  </tr>
	<% end %>
	</table>
	
</p>
<% params[:items] = @items %>
<p><%= submit_tag 'Realizar Pedido' %></p>
<% end %>


<%= link_to 'Listado de Pedidos', pedidos_path %>

app/views/pedidos/responder_pedido.html.erb
<% @items = Item.find(:all, :conditions =>  ["pedido_id = ? ", @pedido.id]) %>


<script>
	
$(function(){
	$(".datepicker").datepicker( {dateFormat: 'dd/mm/yy', showOn:'both'} );
	
});

</script>

<h1>Responder a Pedido</h1>

<%= form_for (@pedido) do |f| -%>
      <% @pedido.errors.full_messages.each do |msg| %>
	    <p><%= msg %></p>
	  <% end %>

<p> 
	<%= label_tag 'Codigo: ' %> <%= (@pedido.Codigo).upcase %><br />
	<%= f.hidden_field :Codigo %>
</p>

<fieldset>
		<legend><h2>Productos en Pedido</h2></legend>
		<p>
		  <b>Items:</b>
		  <p>
			<table>
			  <tr>
			    <th>Categoria</th>
			  	<th>Familia</th>
			  	<th>Producto</th>
			  	<th>Presentacion</th>
			    <th>Codigo</th>
			    <th>Precio</th>
			    <th>Cantidad</th>
			    <th>Total</th>
			  </tr>
			
			<% @items.each do |item| %>
			  <% if item.cantidad > 0 %>
				  <tr>
				    <td><%= item.prod.fam.categ.Nombre %></td>
				  	<td><%= item.prod.fam.Nombre %></td>
				    <td><%= item.prod.Nombre %></td>
				    <td><%= item.prod.Presentacion %></td>
				    <td><%= item.prod.Codigo %></td>
				    <td><%= number_to_currency(item.prod.Precio, :precision => 2) %></td>
				    <td><%= item.cantidad %></td>
				    <td><%= number_to_currency(item.cantidad.to_i * item.prod.Precio, :precision => 2) %></td>
				    <% @sumTot = @sumTot + (item.cantidad.to_i * item.prod.Precio) %>
				  </tr>
			  <% end %>
			<% end %>
				  <tr>
				    <td></td>
				  	<td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td>Subtotal</td>
				    <td><%= number_to_currency(@sumTot, :precision => 2) %></td>
				  </tr>
				  <tr>
				    <td></td>
				  	<td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td>Descuento</td>
				    <td><%= number_to_percentage(@pedido.user.Descuento * 100, :precision => 2 ) %></td>
				  </tr>
				  <tr>
				    <td></td>
				  	<td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td>IVA</td>
				    <td><%= number_to_currency(0, :precision => 2) %></td>
				  </tr>
				  <tr>
				    <td></td>
				  	<td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td></td>
				    <td><b>Total</b></td>
				    <td><%= @pedido.Total %></td>
				  </tr>
			</table>
				
		  </p>
		</p>
</fieldset>

<fieldset>
		<legend><h2>Respuesta</h2></legend>



		<p><%= f.hidden_field :Total%></p>
		<p><%= f.hidden_field :id_usuario %> </p>
		<p><%= f.hidden_field :FechaPedido %></p>
		
		<p>
			<%= f.label 'Estado de Pedido' %><br />
			<%= f.collection_select :idEstado, EstadoPedido.all, :id, :Nombre %>
		</p>
		
		<p>
			<%= label_tag 'Fecha de Entrega' %><br />
			<%= f.text_field  :FechaEntrega,  :class => :datepicker , :value => (@pedido.FechaEntrega.blank? ? (DateTime.now + 2).strftime("%d/%m/%Y") : @pedido.FechaEntrega.strftime('%d/%m/%Y')) %>
		</p>
		
		<p>
		    <%= f.label 'Comentarios' %><br />
		    <%= f.text_area :Comentarios %>
		</p>
		<%= @test1 %><br />
		<%= @test2 %>
</fieldset>

<p><%= submit_tag 'Responder al Pedido' %></p>
<% end %>



<%= link_to 'Volver al Pedido', @pedido %> |
<%= link_to 'Listado de Pedidos', pedidos_path %>

app/views/pedidos/show.html.erb
<h1>Pedido: <%= @pedido.Codigo %></h1>

<p>
  <b>Usuario:</b>
  <%= @pedido.user.Username %>
</p>

<p>
  <b>Codigo:</b>
  <%= @pedido.Codigo %>
</p>

<p>
  <b>Estado:</b>
  <%= @pedido.pestado.Nombre %>
</p>

<p>
  <b>Fecha de Pedido:</b>
  <%= @pedido.FechaPedido %>
</p>

<p>
  <b>Fecha de Entrega:</b>
  <%= @pedido.FechaEntrega %>
</p>

<p>
  <b>Comentarios:</b>
  <%= @pedido.Comentarios %>
</p>

<p>
  <b>Items:</b>
  <p>
	<table>
	  <tr>
	    <th>Categoria</th>
	  	<th>Familia</th>
	  	<th>Producto</th>
	  	<th>Presentacion</th>
	    <th>Codigo</th>
	    <th>Precio</th>
	    <th>Cantidad</th>
	    <th>Total</th>
	  </tr>
	
	<% @items.each do |item| %>
	  <% if item.cantidad > 0 %>
		  <tr>
		    <td><%= item.prod.fam.categ.Nombre %></td>
		  	<td><%= item.prod.fam.Nombre %></td>
		    <td><%= item.prod.Nombre %></td>
		    <td><%= item.prod.Presentacion %></td>
		    <td><%= item.prod.Codigo %></td>
		    <td><%= number_to_currency(item.prod.Precio, :precision => 2) %></td>
		    <td><%= item.cantidad %></td>
		    <td><%= number_to_currency(item.cantidad.to_i * item.prod.Precio, :precision => 2) %></td>
		    <% @sumTot += (item.cantidad.to_i * item.prod.Precio) %>
		  </tr>
	  <% end %>
	<% end %>
		  <tr>
		    <td></td>
		  	<td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td>Subtotal</td>
		    <td><%= number_to_currency(@sumTot, :precision => 2) %></td>
		  </tr>
		  <tr>
		    <td></td>
		  	<td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td>Descuento (<%= number_to_percentage(@pedido.user.Descuento * 100, :precision => 2 ) %> &#37;)</td>
		    <td><%= number_to_currency(@pedido.user.Descuento * @sumTot, :precision => 2 ) %></td>
		  </tr>
		  <tr>
		    <td></td>
		  	<td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td>IVA (12.00&#37;)</td>
		    <td><%= number_to_currency(0, :precision => 2) %></td>
		  </tr>
		  <tr>
		    <td></td>
		  	<td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td></td>
		    <td><b>Total</b></td>
		    <td><%= @pedido.Total %></td>
		  </tr>
	</table>
		
  </p>
</p>


<% if session[:Usuario_idTP] == 1 %>
	<%= link_to 'Editar', edit_pedido_path(@pedido) %> |
<% end %>
<% if session[:Usuario_idTP] == 2 %>
	<%= link_to 'Responder a Pedido', :controller => "pedidos" ,  :id => @pedido , :action => "responder_pedido" %> |
<% end %>
<% if session[:Usuario_idTP] == 4 %>
	<!-- incluir cambiar orden -->
<% end %>

<%= link_to 'Listado de Pedidos', pedidos_path %>