config/routes.rb
DisMardisOrdering::Application.routes.draw do
  get  "usuarios/cambiar_password"
  post "usuarios/cambiar_password"
  
  resources :estado_pedidos

  resources :provincia

  resources :ciudads

  resources :familia

  resources :categoria

  resources :proveedors

  get  "usuarios/login"
  post "usuarios/login"
  
  get  "usuarios/logout"
  
  get  "usuarios/nuevo_gerente"
  post "usuarios/nuevo_gerente"
  get  "usuarios/nuevo_cajero"
  post "usuarios/nuevo_cajero"
  get  "usuarios/nuevo_cliente"
  post "usuarios/nuevo_cliente"

  resources :pedidos
  match 'pedidos/:id/responder_pedido', :to => 'pedidos#responder_pedido'
  
  
  resources :session
  resources :productos

  resources :agencia

  resources :tipo_usuarios

  resources :usuarios

  get  "home/index"
  get  "home/forbidden"

  root :to => 'home#index'

end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :Usuario
end

app/controllers/tipo_usuarios_controller.rb
class TipoUsuariosController < ApplicationController
  before_filter :check_permissions
  
  # GET /tipo_usuarios
  # GET /tipo_usuarios.json
  def index
    @tipo_usuarios = TipoUsuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tipo_usuarios }
    end
  end

  # GET /tipo_usuarios/1
  # GET /tipo_usuarios/1.json
  def show
    @tipo_usuario = TipoUsuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tipo_usuario }
    end
  end

  # GET /tipo_usuarios/new
  # GET /tipo_usuarios/new.json
  def new
    @tipo_usuario = TipoUsuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tipo_usuario }
    end
  end

  # GET /tipo_usuarios/1/edit
  def edit
    @tipo_usuario = TipoUsuario.find(params[:id])
  end

  # POST /tipo_usuarios
  # POST /tipo_usuarios.json
  def create
    @tipo_usuario = TipoUsuario.new(params[:tipo_usuario])

    respond_to do |format|
      if @tipo_usuario.save
        format.html { redirect_to tipo_usuarios_path, notice: 'Tipo usuario fue creado exitosamente.' }
        format.json { render json: @tipo_usuario, status: :created, location: @tipo_usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @tipo_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_usuarios/1
  # PUT /tipo_usuarios/1.json
  def update
    @tipo_usuario = TipoUsuario.find(params[:id])

    respond_to do |format|
      if @tipo_usuario.update_attributes(params[:tipo_usuario])
        format.html { redirect_to @tipo_usuario, notice: 'Tipo usuario fue actualizado existosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tipo_usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_usuarios/1
  # DELETE /tipo_usuarios/1.json
  def destroy
    @tipo_usuario = TipoUsuario.find(params[:id])
    @tipo_usuario.destroy

    respond_to do |format|
      format.html { redirect_to tipo_usuarios_url }
      format.json { head :no_content }
    end
  end
  
  private
    def check_permissions
      if session[:Usuario_idTP] == 3 || session[:Usuario_idTP] == 4
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 2 && self.action_name == 'destroy'
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
    end
end

app/helpers/tipo_usuarios_helper.rb
module TipoUsuariosHelper
end

app/views/tipo_usuarios/_form.html.erb
<%= form_for(@tipo_usuario) do |f| %>
  <% if @tipo_usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_usuario.errors.count, "error") %> prohibited this tipo_usuario from being saved:</h2>

      <ul>
      <% @tipo_usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :Nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_usuarios/edit.html.erb
<h1>Editing tipo_usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_usuario %> |
<%= link_to 'Back', tipo_usuarios_path %>

app/views/tipo_usuarios/index.html.erb
<h1>Listing tipo_usuarios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tipo_usuarios.each do |tipo_usuario| %>
  <tr>
    <td><%= tipo_usuario.Nombre %></td>
    <td><%= link_to 'Show', tipo_usuario %></td>
    <td><%= link_to 'Edit', edit_tipo_usuario_path(tipo_usuario) %></td>
    <td><%= button_to  'Destroy', tipo_usuario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tipo usuario', new_tipo_usuario_path %>

app/views/tipo_usuarios/new.html.erb
<h1>New tipo_usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_usuarios_path %>

app/views/tipo_usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @tipo_usuario.Nombre %>
</p>


<%= link_to 'Edit', edit_tipo_usuario_path(@tipo_usuario) %> |
<%= link_to 'Back', tipo_usuarios_path %>