config/routes.rb
DisMardisOrdering::Application.routes.draw do
  get  "usuarios/cambiar_password"
  post "usuarios/cambiar_password"
  
  resources :estado_pedidos

  resources :provincia

  resources :ciudads

  resources :familia

  resources :categoria

  resources :proveedors

  get  "usuarios/login"
  post "usuarios/login"
  
  get  "usuarios/logout"
  
  get  "usuarios/nuevo_gerente"
  post "usuarios/nuevo_gerente"
  get  "usuarios/nuevo_cajero"
  post "usuarios/nuevo_cajero"
  get  "usuarios/nuevo_cliente"
  post "usuarios/nuevo_cliente"

  resources :pedidos
  match 'pedidos/:id/responder_pedido', :to => 'pedidos#responder_pedido'
  
  
  resources :session
  resources :productos

  resources :agencia

  resources :tipo_usuarios

  resources :usuarios

  get  "home/index"
  get  "home/forbidden"

  root :to => 'home#index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :prov, :class_name => "Proveedor", :foreign_key => "idProveedor"
  belongs_to :fam, :class_name => "Familium", :foreign_key => "idFamilia"
  has_many :Pedido, :through => Item
  
  
  validates :Nombre       ,  :length => {
                            :minimum   => 2,
                            :maximum   => 25,
                            :too_short => ": Debe de tener por lo menos %{count} letras.",
                            :too_long  => ": Debe de tener un maximo de %{count} letras."
                          },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }
  
  validates :Codigo       ,  :length => {
                            :minimum   => 1,
                            :maximum   => 6,
                            :too_short => ": Debe de tener por lo menos %{count} letras.",
                            :too_long  => ": Debe de tener un maximo de %{count} letras."
                          },
                          :presence => { :message => ": No puede ser ingresado como en blanco." },
                          :uniqueness => { :case_sensitive => false ,  :message => ": No es unico." }
                          
  validates :idFamilia    , :numericality => { :only_integer => true },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }
                          
  validates :Precio       , :numericality => { :message => ": %{value} No es un valor valido." },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }                          
                          
   validates :idProveedor , :numericality => { :only_integer => true },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }                         
                          
  validates :Presentacion ,  :length => {
                            :minimum   => 1,
                            :maximum   => 25,
                            :too_short => ": Debe de tener por lo menos %{count} letras.",
                            :too_long  => ": Debe de tener un maximo de %{count} letras."
                          },
                          :presence => { :message => ": No puede ser ingresado como en blanco." }
                          
  
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_filter :check_permissions
  
  # GET /productos
  # GET /productos.json
  def index
    #@productos

    if session[:Usuario_idTP] == 1 ||  session[:Usuario_idTP] == 2
      @productos = Producto.all
    else
      @productos = Producto.find(:all, :conditions => ["estado = ?" , true ] )
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @productos }
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
    @producto = Producto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/new
  # GET /productos/new.json
  def new
    @producto = Producto.new
    @numFami = Familium.count
    @numProv = Proveedor.count
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @producto }
    end
  end

  # GET /productos/1/edit
  def edit
    @producto = Producto.find(params[:id])
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(params[:producto])
    if ( /^[\d]+(\.[\d]+){0,1}$/ === @producto.Precio )
      @producto.Precio = number_with_precision( @producto.Precio , :precision => 2)
    end
    respond_to do |format|
      if @producto.save
        format.html { redirect_to productos_path, notice: 'El producto fue creado exitosamente.' }
        format.json { render json: @producto, status: :created, location: @producto }
      else
        format.html { render action: "new" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /productos/1
  # PUT /productos/1.json
  def update
    @producto = Producto.find(params[:id])
    if ( /^[\d]+(\.[\d]+){0,1}$/ === @producto.Precio )
      @producto.Precio = number_with_precision( @producto.Precio , :precision => 2)
    end
    respond_to do |format|
      if @producto.update_attributes(params[:producto])
        format.html { redirect_to @producto, notice: 'El producto fue actualizado existosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end
  
  private
    def check_permissions
      if (session[:Usuario_idTP] == 3 || session[:Usuario_idTP] == 4) && (self.action_name != 'index' && self.action_name != 'show')
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
      if session[:Usuario_idTP] == 2 && self.action_name == 'destroy'
        redirect_to  :controller => 'home', :action => 'forbidden'
        return
      end
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :idEmpresa %><br />
    <%= f.number_field :idEmpresa %>
  </div>
  <div class="field">
    <%= f.label :Codigo %><br />
    <%= f.text_field :Codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<script>
	
$(function(){
	$(".datepicker").datepicker( {dateFormat: 'dd/mm/yy', showOn:'both'} );
	
});

</script>

<h1>Editar Producto</h1>

<%= form_for (@producto) do |f| -%>
	
	<% @producto.errors.full_messages.each do |msg| %>
	  <p><%= msg %></p>
	<% end %>
	  
	<fieldset>
	  <legend><h2>Formulario</h2></legend>
	  <p>
		<%= label_tag 'Nombre' %><br />
	    <%= f.text_field :Nombre , :autocomplete => :off%>
	  </p>
	  <p>
		<%= f.label 'Codigo' %><br />
		<%= f.text_field :Codigo , :autocomplete => :off%>
	  </p>
      <p>
	    <%= label_tag 'Proveedor' %><br />
	    <%= f.collection_select :idProveedor, Proveedor.all, :id, :Nombre %>
	  </p>
	  <p>
	    <%= label_tag 'Familia' %><br />
	    <%= f.collection_select :idFamilia, Familium.all, :id, :Nombre %>
	  </p>
	  <p>
	    <%= label_tag 'Precio' %><br />
	    <%= f.text_field :Precio , :autocomplete => :off, :value => number_with_precision( @producto.Precio , :precision => 2)%>
	  </p>
	  <p>
	    <%= label_tag 'Estado' %><br />
	    <%= f.check_box :estado%> <%= label_tag 'Activo' %>
	  </p>
	  <p>
	    <%= label_tag 'Presentacion' %><br />
	    <%= f.text_field :Presentacion , :autocomplete => :off%>
	  </p>
	  
	  
	  <p>
		    <%= label_tag 'Fecha de Inicio' %><br />
		    <%= f.text_field  :FechaInicio,  :class => :datepicker , :value => (@producto.FechaInicio.blank? ? DateTime.now.strftime("%d/%m/%Y") : @producto.FechaInicio.strftime('%d/%m/%Y')) %>
	  </p>
 	  <p>
		    <%= label_tag 'Fecha de Caducidad' %><br />
		    <%= f.text_field  :FechaCaducidad,  :class => :datepicker , :value => (@producto.FechaCaducidad.blank? ? (DateTime.now + 14).strftime("%d/%m/%Y") : @producto.FechaCaducidad.strftime('%d/%m/%Y'))%>
	  </p>
    </fieldset>
  
  <p><%= f.submit "Actualizar Producto" %></p>
<% end %>

<%= link_to 'Volver a ' + @producto.Nombre, @producto %> |
<%= link_to 'Listado de Productoss', productos_path %>

app/views/productos/index.html.erb
<h1>Listado de Productos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Proveedor</th>
    <th>Codigo</th>
    <th>Familia</th>
    <th>Precio (PVP)</th>
    
    <% if session[:Usuario_idTP] == 1 || session[:Usuario_idTP] == 2 %>
    	<th>Estado</th>
    	<th></th>
    <% end %>
    <% if session[:Usuario_idTP] == 1 %>
	 
	 	<th></th> 
	 
	<% end %>
  </tr>

<% @productos.each do |producto| %>
  <tr>
    <td><%= link_to producto.Nombre, producto %></td>
    <td><%= producto.prov.Nombre %></td>
    <td><%= producto.Codigo %></td>
    <td><%= producto.fam.Nombre %></td>
    <td><%= number_to_currency(producto.Precio , :precision => 2) %></td>
    
    <% if session[:Usuario_idTP] == 1 ||  session[:Usuario_idTP] == 2 %>
    	<td align="center"><% if producto.estado %> <%= image_tag "/assets/green.jpg" %> <% else %> <%= image_tag "/assets/red.jpg" %> <% end %> </td>
    	<td><%= link_to 'Editar', edit_producto_path(producto) %></td>
    <% end %>
    <% if session[:Usuario_idTP] == 1 %>
	 
	 	<td><%= button_to  'Borrar', producto, confirm: 'Esta seguro?', method: :delete %></td>
	 
	<% end %>
  </tr>
<% end %>
</table>

<br />

<% if session[:Usuario_idTP] == 1 || session[:Usuario_idTP] == 2 %>
	<%= link_to 'Nuevo Producto', new_producto_path %>
<% end %>

app/views/productos/new.html.erb
<script>
	
$(function(){
	$(".datepicker").datepicker( {dateFormat: 'dd/mm/yy', showOn:'both'} );
	
});


$(document).ready(function(){
        var search = "#Precio";
        var chars = $(search).attr('placeholder').split('');
        $.each(chars, function(i, v){
          setTimeout(function() {
            $(search).val((chars.slice(0, i+1).join('')));
          }, 100*i);
        });
      });
</script>


<h1>Nuevo Producto</h1>


<% if @numProv != 0 && @numFami != 0 %>
  <%= form_for :producto, :url => productos_path do |f| -%>
      <% @producto.errors.full_messages.each do |msg| %>
	    <p><%= msg %></p>
	  <% end %>
	  <div>
	  <fieldset>
		<legend><h2>Formulario</h2></legend>
		  
		  <p>
			<%= label_tag 'Nombre' %><br />
		    <%= f.text_field :Nombre , :autocomplete => :off%>
		  </p>
		  <p>
		    <%= label_tag 'Codigo' %><br />
		    <%= f.text_field :Codigo , :autocomplete => :off%>
		  </p>
		  <p>
		    <%= label_tag 'Proveedor' %><br />
		    <%= f.collection_select :idProveedor, Proveedor.all, :id, :Nombre %>
		  </p>
		  <p>
		    <%= label_tag 'Familia' %><br />
		    <%= f.collection_select :idFamilia, Familium.all, :id, :Nombre %>
		  </p>
		  <p>
		    <%= label_tag 'Precio' %><br />
		    <%= f.text_field :Precio , :autocomplete => :off , :placeholder => "0.00"%>
		  </p>
		  <p>
		    <%= label_tag 'Estado' %><br />
		    <%= f.check_box :estado, {checked: true}%> <%= label_tag 'Activo' %>
		  </p>
		  <p>
		    <%= label_tag 'Presentacion' %><br />
		    <%= f.text_field :Presentacion , :autocomplete => :off%>
		  </p>
		  <p>
		    <%= label_tag 'Fecha de Inicio' %><br />
		    <%= f.text_field  :FechaInicio,  :class => :datepicker , :value => (@producto.FechaInicio.blank? ? DateTime.now.strftime("%d/%m/%Y") : @producto.FechaInicio.strftime('%d/%m/%Y')) %>
		  </p>
		  <p>
		    <%= label_tag 'Fecha de Caducidad' %><br />
		    <%= f.text_field  :FechaCaducidad,  :class => :datepicker , :value => (@producto.FechaCaducidad.blank? ? (DateTime.now + 14).strftime("%d/%m/%Y") : @producto.FechaCaducidad.strftime('%d/%m/%Y'))%>
		  </p>

	  
	  </fieldset>
	  </div>
	  
	  <p><%= submit_tag 'Crear Producto' %></p>
	<% end %>
<% else %>
	Para crear un nuevo producto por favor crear <%= link_to 'familias de producto', familia_path %> y <%= link_to 'proveedores', proveedors_path %> primero.
	<br /><br /><br />
<% end %>	


<%= link_to 'Listado de Productos', productos_path %>

app/views/productos/show.html.erb
<h1>Producto: <%= @producto.Nombre %></h1>

<p>
  <b>Nombre:</b>
  <%= @producto.Nombre %>
</p>

<p>
  <b>Codigo:</b>
  <%= @producto.Codigo %>
</p>

<p>
  <b>Familia:</b>
  <%= @producto.fam.Nombre %>
</p>

<p>
  <b>Precio:</b>
  <%= number_to_currency(@producto.Precio , :precision => 2) %>
</p>

<p>
  <b>Estado:</b>
  <% if @producto.estado %>
  	Activo
  <% else %>
  	Desactivado
  <% end %>
</p>

<p>
  <b>Fecha de Inicio:</b>
  <%= @producto.FechaInicio %>
</p>

<p>
  <b>Fecha de Caducidad:</b>
  <%= @producto.FechaCaducidad %>
</p>


<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Listado de Productos', productos_path %>